name: CI Pipeline

on:
  pull_request:
  types:
    - opened
  branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
